port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true