port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      path: /h2-console
      enabled: true

  cache:
    cache-names: findPricesCache
    caffeine:
      spec: maximumSize=5,expireAfterWrite=10m

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      pricesCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true